FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

COPY cnn_face_model.keras /app/cnn_face_model.keras

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
